#! /opt/local/bin/bash
# first arg	: the path to Sublime Text 2's folder Packages/User/Build
# second arg	: the name of the entry file
# third arg	; the optional debug switch

# stop running instances of node and/or node inspector
"$1/stop" "$1"

# creating new template bundle if necessary
if [[ -e "`dirname $2`/gruntfile.js" ]]; then 
	echo "running grunt with `dirname $2`/gruntfile.js"
	grunt --no-color
else
	echo "not running grunt: `dirname $2`/gruntfile.js not available"
fi

# creating one modularized JS package
if [[ -e "`dirname $2`/public/js/main.js" ]]; then 
	echo "running browserify with `dirname $2`/public/js/main.js" 
	cd "`dirname $2`/public/js" 
	browserify main.js -d -o bundle.js
else
	echo "not running browserify: `dirname $2`/public/js/main.js not available"
fi

# starting the node server
NODE_ENV=development node $3 $2 &
pid=$!
while [[ -z "$pid" ]]; do
	sleep 1
done
echo $pid > "$1/pid.node"
echo "running node $3 ($pid)"
echo "NODE_ENV=development"

# starting the node inspector
if [[ $3 = "--debug" ]] || [[ $3 = "--debug-brk" ]]; then
	node-inspector &
	pid=$!
	while [[ -z "$pid" ]]; do
		sleep 1
	done
	echo $pid > "$1/pid.inspector"
	echo "running node-inspector ($pid)"
fi
