#! /opt/local/bin/bash
# first arg	: the path to Sublime Text 2's folder Packages/User/Build
# second arg	: the name of the entry file
# third arg	; the optional debug switch

"$1/stop" "$1"

echo "NODE_ENV=development"

NODE_ENV=development node $3 $2 &
pid=$!
while [[ -z "$pid" ]]; do
	sleep 1
done
echo $pid > "$1/pid.node"
echo "starting node ($pid)"


if [[ $3 = "--debug" ]] || [[ $3 = "--debug-brk" ]]; then
	node-inspector &
	pid=$!
	while [[ -z "$pid" ]]; do
		sleep 1
	done
	echo $pid > "$1/pid.inspector"
	echo "starting node-inspector ($pid)"
fi
