#! /opt/local/bin/bash
# first arg	: the path to Sublime Text 2's folder Packages/User/Build
# second arg	: the name of the entry file
# third arg	; the optional debug switch

# stop running instances of node and/or node inspector
"$1/stop" "$1"

# creating new template bundle if necessary
echo "!: running grunt ..."
grunt mt --no-color

# creating one modularized JS package
echo "!: running browserify ..."
cd "`dirname $2`/public/js" 
browserify main.js -d -o bundle.js

# starting the node server
NODE_ENV=development node $3 $2 &
pid=$!
while [[ -z "$pid" ]]; do
	sleep 1
done
echo $pid > "$1/pid.node"
echo "!: starting node $3 ($pid)"
echo "NODE_ENV=development"

# starting the node inspector
if [[ $3 = "--debug" ]] || [[ $3 = "--debug-brk" ]]; then
	node-inspector &
	pid=$!
	while [[ -z "$pid" ]]; do
		sleep 1
	done
	echo $pid > "$1/pid.inspector"
	echo "!: starting node-inspector ($pid)"
fi
