#! /bin/bash
# first arg		: the path to Sublime Text 2's folder Packages/User/Build

# stop process if we think we started it
if [[ -e "$1/pid.node" ]]; then 
	pid=$(cat "$1/pid.node")

	test1=$(ps axo pid,command|grep "$pid"|grep "node"|grep -v grep|sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

	if [[ "$test1" ]]; then
		echo "stopping $test1"
		kill -s SIGTERM $pid
	else
		echo "deleting stale pid.node; no process stopped"
	fi
	rm "$1/pid.node"
fi

if [[ -e "$1/pid.inspector" ]]; then 
	pid=$(cat "$1/pid.inspector")

	test1=$(ps axo pid,command|grep "$pid"|grep "inspector"|grep -v grep|sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

	if [[ "$test1" ]]; then
		echo "stopping $test1"
		kill -s SIGTERM $pid
	else
		echo "deleting stale pid.inspector; no process stopped"
	fi
	rm "$1/pid.inspector"
fi
